name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Executar testes?'
        required: true
        default: 'true'
        type: boolean
      run_build:
        description: 'Executar build?'
        required: true
        default: 'true'
        type: boolean

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  build:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.run_build == 'true' }}
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - run: mvn clean install

  test:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.run_tests == 'true' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: mvn test

