name: Abrir Issue com GITHUB_TOKEN

on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  open-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Abrir issue se PROD_TOKEN estiver ausente
        if: ${{ secrets.PROD_TOKEN == '' }}
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues \
          -d '{"title":"PROD_TOKEN ausente","body":"Favor configurar o segredo PROD_TOKEN."}'
