name: Runner Auto-Hospedado

on: [push]

jobs:
  run-on-self-hosted:
    runs-on: self-hosted
    steps:
      - name: Exibir informações do sistema
        run: |
          uname -a
          java -version
      - name: Instalar software adicional (ex: tree)
        run: |
          sudo apt-get update
          sudo apt-get install -y tree
          tree .
