name: Uso de Variáveis e Segredos

on: [push]

jobs:
  demo-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar variáveis
        run: |
          echo "Modo da aplicação: ${{ vars.APP_MODE }}"
          echo "Email de suporte: ${{ vars.SUPPORT_EMAIL }}"
      - name: Simular passo sensível
        run: echo "Usando PROD_TOKEN=${{ secrets.PROD_TOKEN }}"
